name: localizare1
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  flutter_redux: ^0.10.0
  json_annotation: ^4.7.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  build_runner: ^2.3.3

  #flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
